services:
  backend:
    build:
      context: ./backend
    container_name: secureview-backend
    environment:
      PORT: 3000
      JWT_SECRET: change-this-jwt-secret
      JWT_EXPIRE: 12h
      DB_PATH: /app/data/app.db
      STORAGE_ROOT: /app/storage
      FRONTEND_ORIGIN: http://localhost:8080
      INITIAL_PASSWORD_KEY: 0123456789abcdef0123456789abcdef
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_PASSWORD: Admin@123456
      FORCE_RESET_ADMIN_PASSWORD: "false"
      AUTO_SYNC_DEFAULT_ADMIN_PASSWORD: "true"
    volumes:
      - sqlite_data:/app/data
      - storage_data:/app/storage
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    container_name: secureview-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  sqlite_data:
  storage_data:
